services:

  mysql:
    image: mysql:8.0
    container_name: mandal-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mandalsetu_db
      MYSQL_USER: mandal
      MYSQL_PASSWORD: mandal123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: mandal-backend
    restart: unless-stopped

    environment:
      NODE_ENV: production
      PORT: 5000

      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: mandal
      DB_PASSWORD: mandal123
      DB_NAME: mandalsetu_db

      JWT_SECRET: mandal-testing-secret-123

    ports:
      - "5000:5000"

    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./backend/uploads:/app/uploads


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://54.87.168.32:5000/api
        VITE_BACKEND_URL: http://54.87.168.32:5000

    container_name: mandal-frontend
    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend


volumes:
  mysql_data:
